{
 "title": "Dashboard Debug",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "METERS (C1-C5)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "proxydict_C1" },
    { "expr": "proxydict_C2" },
    { "expr": "proxydict_C3" },
    { "expr": "proxydict_C4" },
    { "expr": "proxydict_C5" }
   ]
  },
  {
   "title": "VALVES (Y1)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "proxydict_Y1" }
   ]
  },
  {
   "title": "VALVES (Y2)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
   "targets": [
    { "expr": "proxydict_Y2" }
   ]
  },
  {
   "title": "VALVES (Y3)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
   "targets": [
    { "expr": "proxydict_Y3" }
   ]
  },
  {
   "title": "PUMPS (P1)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 20 },
   "targets": [
    { "expr": "proxydict_P1" }
   ]
  },
  {
   "title": "PUMPS (P2)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 24 },
   "targets": [
    { "expr": "proxydict_P2" }
   ]
  },
  {
   "title": "PUMPS (P3)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 28 },
   "targets": [
    { "expr": "proxydict_P3" }
   ]
  },
  {
   "title": "PUMPS (P4)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 32 },
   "targets": [
    { "expr": "proxydict_P4" }
   ]
  }
 ]
}